name: ductuch_master
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.1
  flutter_tts: ^4.2.3
  get: ^4.7.2
  google_fonts: ^6.3.2
  persistent_bottom_nav_bar: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - lib/Data/json/
    - assets/learn_module/
# assets:
#     - Assets/Images/
#     - Assets/Icons/
    # - assets/fonts/