name: ductuch_master
description: "A new Flutter project."
publish_to: 'none'
version: 2.0.0+5

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.1
  flutter_tts: ^4.2.3
  get: ^4.7.2
  google_fonts: ^6.3.2
  persistent_bottom_nav_bar: ^6.2.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - lib/Data/json/
    - assets/learn_module/
  fonts:
    - family: Comfortaa
      fonts:
        
        - asset: assets/Fonts/Comfortaa/Comfortaa-Regular.ttf
          weight: 400
        - asset: assets/Fonts/Comfortaa/Comfortaa-Medium.ttf
          weight: 500
        - asset: assets/Fonts/Comfortaa/Comfortaa-SemiBold.ttf
          weight: 600
        - asset: assets/Fonts/Comfortaa/Comfortaa-Bold.ttf
          weight: 700
    - family: Comfortaa-Regular
      fonts:
        - asset: assets/Fonts/Comfortaa/Comfortaa-Regular.ttf
    - family: Comfortaa-Medium
      fonts:
        - asset: assets/Fonts/Comfortaa/Comfortaa-Medium.ttf
    - family: Comfortaa-SemiBold
      fonts:
        - asset: assets/Fonts/Comfortaa/Comfortaa-SemiBold.ttf
    - family: Comfortaa-Bold
      fonts:
        - asset: assets/Fonts/Comfortaa/Comfortaa-Bold.ttf
